// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package db

import (
	"context"
)

const binding = `-- name: Binding :one
SELECT binding FROM bindings WHERE id = $1
`

func (q *Queries) Binding(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, binding, id)
	var binding string
	err := row.Scan(&binding)
	return binding, err
}

const claim = `-- name: Claim :one
SELECT claim FROM claims WHERE id = $1
`

func (q *Queries) Claim(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, claim, id)
	var claim string
	err := row.Scan(&claim)
	return claim, err
}

const claimIdentitiesByOwnerBefore = `-- name: ClaimIdentitiesByOwnerBefore :many
SELECT id, owner_identity FROM claims WHERE owner_kind = $1 AND owner_authority = $2 AND id < $3 ORDER BY id DESC LIMIT $4
`

type ClaimIdentitiesByOwnerBeforeParams struct {
	OwnerKind      string
	OwnerAuthority string
	ID             string
	Limit          int32
}

type ClaimIdentitiesByOwnerBeforeRow struct {
	ID            string
	OwnerIdentity string
}

func (q *Queries) ClaimIdentitiesByOwnerBefore(ctx context.Context, arg ClaimIdentitiesByOwnerBeforeParams) ([]ClaimIdentitiesByOwnerBeforeRow, error) {
	rows, err := q.db.Query(ctx, claimIdentitiesByOwnerBefore,
		arg.OwnerKind,
		arg.OwnerAuthority,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimIdentitiesByOwnerBeforeRow{}
	for rows.Next() {
		var i ClaimIdentitiesByOwnerBeforeRow
		if err := rows.Scan(&i.ID, &i.OwnerIdentity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimIdentitiesByOwnerDesc = `-- name: ClaimIdentitiesByOwnerDesc :many
SELECT id, owner_identity FROM claims WHERE owner_kind = $1 AND owner_authority = $2 ORDER BY id DESC LIMIT $3
`

type ClaimIdentitiesByOwnerDescParams struct {
	OwnerKind      string
	OwnerAuthority string
	Limit          int32
}

type ClaimIdentitiesByOwnerDescRow struct {
	ID            string
	OwnerIdentity string
}

func (q *Queries) ClaimIdentitiesByOwnerDesc(ctx context.Context, arg ClaimIdentitiesByOwnerDescParams) ([]ClaimIdentitiesByOwnerDescRow, error) {
	rows, err := q.db.Query(ctx, claimIdentitiesByOwnerDesc, arg.OwnerKind, arg.OwnerAuthority, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimIdentitiesByOwnerDescRow{}
	for rows.Next() {
		var i ClaimIdentitiesByOwnerDescRow
		if err := rows.Scan(&i.ID, &i.OwnerIdentity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimsByOwnerAfter = `-- name: ClaimsByOwnerAfter :many
SELECT id, owner_identity, claim FROM claims WHERE owner_kind = $1 AND owner_authority = $2 AND id > $3 ORDER BY id LIMIT $4
`

type ClaimsByOwnerAfterParams struct {
	OwnerKind      string
	OwnerAuthority string
	ID             string
	Limit          int32
}

type ClaimsByOwnerAfterRow struct {
	ID            string
	OwnerIdentity string
	Claim         string
}

func (q *Queries) ClaimsByOwnerAfter(ctx context.Context, arg ClaimsByOwnerAfterParams) ([]ClaimsByOwnerAfterRow, error) {
	rows, err := q.db.Query(ctx, claimsByOwnerAfter,
		arg.OwnerKind,
		arg.OwnerAuthority,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimsByOwnerAfterRow{}
	for rows.Next() {
		var i ClaimsByOwnerAfterRow
		if err := rows.Scan(&i.ID, &i.OwnerIdentity, &i.Claim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBinding = `-- name: InsertBinding :exec
INSERT INTO bindings (id, digest, binding) VALUES ($1, $2, $3)
`

type InsertBindingParams struct {
	ID      string
	Digest  string
	Binding string
}

func (q *Queries) InsertBinding(ctx context.Context, arg InsertBindingParams) error {
	_, err := q.db.Exec(ctx, insertBinding, arg.ID, arg.Digest, arg.Binding)
	return err
}

const insertClaim = `-- name: InsertClaim :exec
INSERT INTO claims (id, owner_kind, owner_authority, owner_identity, state, claim) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertClaimParams struct {
	ID             string
	OwnerKind      string
	OwnerAuthority string
	OwnerIdentity  string
	State          string
	Claim          string
}

func (q *Queries) InsertClaim(ctx context.Context, arg InsertClaimParams) error {
	_, err := q.db.Exec(ctx, insertClaim,
		arg.ID,
		arg.OwnerKind,
		arg.OwnerAuthority,
		arg.OwnerIdentity,
		arg.State,
		arg.Claim,
	)
	return err
}

const updateClaim = `-- name: UpdateClaim :exec
UPDATE claims SET state = $1, claim = $2 WHERE id = $3
`

type UpdateClaimParams struct {
	State string
	Claim string
	ID    string
}

func (q *Queries) UpdateClaim(ctx context.Context, arg UpdateClaimParams) error {
	_, err := q.db.Exec(ctx, updateClaim, arg.State, arg.Claim, arg.ID)
	return err
}
