// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoints.sql

package db

import (
	"context"
)

const checkpoint = `-- name: Checkpoint :one
SELECT next FROM checkpoints WHERE consumer = $1 AND ledger = $2
`

type CheckpointParams struct {
	Consumer string
	Ledger   string
}

func (q *Queries) Checkpoint(ctx context.Context, arg CheckpointParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkpoint, arg.Consumer, arg.Ledger)
	var next int64
	err := row.Scan(&next)
	return next, err
}

const upsertCheckpoint = `-- name: UpsertCheckpoint :exec
INSERT INTO checkpoints (consumer, ledger, next) VALUES ($1, $2, $3)
ON CONFLICT (consumer, ledger) DO UPDATE SET next = EXCLUDED.next
`

type UpsertCheckpointParams struct {
	Consumer string
	Ledger   string
	Next     int64
}

func (q *Queries) UpsertCheckpoint(ctx context.Context, arg UpsertCheckpointParams) error {
	_, err := q.db.Exec(ctx, upsertCheckpoint, arg.Consumer, arg.Ledger, arg.Next)
	return err
}
