// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: common.sql

package db

import (
	"context"
)

const advisoryLock = `-- name: AdvisoryLock :exec
SELECT pg_advisory_xact_lock(hashtext($1::text))
`

func (q *Queries) AdvisoryLock(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, advisoryLock, key)
	return err
}

const recordSchemaVersion = `-- name: RecordSchemaVersion :exec
INSERT INTO twilight_schema (version, applied_at) VALUES ($1, $2)
`

type RecordSchemaVersionParams struct {
	Version   int64
	AppliedAt int64
}

func (q *Queries) RecordSchemaVersion(ctx context.Context, arg RecordSchemaVersionParams) error {
	_, err := q.db.Exec(ctx, recordSchemaVersion, arg.Version, arg.AppliedAt)
	return err
}

const schemaVersion = `-- name: SchemaVersion :one
SELECT COALESCE(MAX(version), 0)::bigint AS version FROM twilight_schema
`

func (q *Queries) SchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, schemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}
