// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package db

import (
	"context"
)

const content = `-- name: Content :one
SELECT data, media_type, durability FROM content WHERE authority = $1 AND key = $2
`

type ContentParams struct {
	Authority string
	Key       string
}

type ContentRow struct {
	Data       []byte
	MediaType  string
	Durability string
}

func (q *Queries) Content(ctx context.Context, arg ContentParams) (ContentRow, error) {
	row := q.db.QueryRow(ctx, content, arg.Authority, arg.Key)
	var i ContentRow
	err := row.Scan(&i.Data, &i.MediaType, &i.Durability)
	return i, err
}

const insertContent = `-- name: InsertContent :exec
INSERT INTO content (authority, key, data, media_type, durability) VALUES ($1, $2, $3, $4, $5)
`

type InsertContentParams struct {
	Authority  string
	Key        string
	Data       []byte
	MediaType  string
	Durability string
}

func (q *Queries) InsertContent(ctx context.Context, arg InsertContentParams) error {
	_, err := q.db.Exec(ctx, insertContent,
		arg.Authority,
		arg.Key,
		arg.Data,
		arg.MediaType,
		arg.Durability,
	)
	return err
}

const updateContentDurability = `-- name: UpdateContentDurability :exec
UPDATE content SET durability = $1 WHERE authority = $2 AND key = $3
`

type UpdateContentDurabilityParams struct {
	Durability string
	Authority  string
	Key        string
}

func (q *Queries) UpdateContentDurability(ctx context.Context, arg UpdateContentDurabilityParams) error {
	_, err := q.db.Exec(ctx, updateContentDurability, arg.Durability, arg.Authority, arg.Key)
	return err
}
