// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: executions.sql

package db

import (
	"context"
)

const executionCommitSeq = `-- name: ExecutionCommitSeq :one
SELECT seq FROM execution_commits WHERE key = $1 AND commit_id = $2
`

type ExecutionCommitSeqParams struct {
	Key      string
	CommitID string
}

func (q *Queries) ExecutionCommitSeq(ctx context.Context, arg ExecutionCommitSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, executionCommitSeq, arg.Key, arg.CommitID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const executionCommitsFrom = `-- name: ExecutionCommitsFrom :many
SELECT seq, body FROM execution_commits WHERE key = $1 AND seq >= $2 ORDER BY seq
`

type ExecutionCommitsFromParams struct {
	Key string
	Seq int64
}

type ExecutionCommitsFromRow struct {
	Seq  int64
	Body string
}

func (q *Queries) ExecutionCommitsFrom(ctx context.Context, arg ExecutionCommitsFromParams) ([]ExecutionCommitsFromRow, error) {
	rows, err := q.db.Query(ctx, executionCommitsFrom, arg.Key, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionCommitsFromRow{}
	for rows.Next() {
		var i ExecutionCommitsFromRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const executionExists = `-- name: ExecutionExists :one
SELECT EXISTS(SELECT 1 FROM executions WHERE key = $1)::boolean AS present
`

func (q *Queries) ExecutionExists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, executionExists, key)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const executionHead = `-- name: ExecutionHead :one
SELECT COALESCE(MAX(seq), -1)::bigint AS last_seq FROM execution_commits WHERE key = $1
`

func (q *Queries) ExecutionHead(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRow(ctx, executionHead, key)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const executionLease = `-- name: ExecutionLease :one
SELECT owner, epoch, lease_until FROM execution_leases WHERE key = $1
`

type ExecutionLeaseRow struct {
	Owner      string
	Epoch      int64
	LeaseUntil int64
}

func (q *Queries) ExecutionLease(ctx context.Context, key string) (ExecutionLeaseRow, error) {
	row := q.db.QueryRow(ctx, executionLease, key)
	var i ExecutionLeaseRow
	err := row.Scan(&i.Owner, &i.Epoch, &i.LeaseUntil)
	return i, err
}

const executionsOwnedBy = `-- name: ExecutionsOwnedBy :many
SELECT e.assignment_key FROM execution_leases l JOIN executions e ON e.key = l.key WHERE l.owner = $1 ORDER BY l.key
`

func (q *Queries) ExecutionsOwnedBy(ctx context.Context, owner string) ([]string, error) {
	rows, err := q.db.Query(ctx, executionsOwnedBy, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var assignment_key string
		if err := rows.Scan(&assignment_key); err != nil {
			return nil, err
		}
		items = append(items, assignment_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertExecution = `-- name: InsertExecution :exec
INSERT INTO executions (key, assignment_key) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING
`

type InsertExecutionParams struct {
	Key           string
	AssignmentKey string
}

func (q *Queries) InsertExecution(ctx context.Context, arg InsertExecutionParams) error {
	_, err := q.db.Exec(ctx, insertExecution, arg.Key, arg.AssignmentKey)
	return err
}

const insertExecutionCommit = `-- name: InsertExecutionCommit :exec
INSERT INTO execution_commits (key, seq, commit_id, body) VALUES ($1, $2, $3, $4)
`

type InsertExecutionCommitParams struct {
	Key      string
	Seq      int64
	CommitID string
	Body     string
}

func (q *Queries) InsertExecutionCommit(ctx context.Context, arg InsertExecutionCommitParams) error {
	_, err := q.db.Exec(ctx, insertExecutionCommit,
		arg.Key,
		arg.Seq,
		arg.CommitID,
		arg.Body,
	)
	return err
}

const insertExecutionLease = `-- name: InsertExecutionLease :exec
INSERT INTO execution_leases (key, owner, epoch, lease_until) VALUES ($1, $2, $3, $4)
`

type InsertExecutionLeaseParams struct {
	Key        string
	Owner      string
	Epoch      int64
	LeaseUntil int64
}

func (q *Queries) InsertExecutionLease(ctx context.Context, arg InsertExecutionLeaseParams) error {
	_, err := q.db.Exec(ctx, insertExecutionLease,
		arg.Key,
		arg.Owner,
		arg.Epoch,
		arg.LeaseUntil,
	)
	return err
}

const renewExecutionLease = `-- name: RenewExecutionLease :exec
UPDATE execution_leases SET lease_until = $1 WHERE key = $2
`

type RenewExecutionLeaseParams struct {
	LeaseUntil int64
	Key        string
}

func (q *Queries) RenewExecutionLease(ctx context.Context, arg RenewExecutionLeaseParams) error {
	_, err := q.db.Exec(ctx, renewExecutionLease, arg.LeaseUntil, arg.Key)
	return err
}

const upsertExecutionLease = `-- name: UpsertExecutionLease :exec
INSERT INTO execution_leases (key, owner, epoch, lease_until) VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE SET owner = EXCLUDED.owner, epoch = EXCLUDED.epoch, lease_until = EXCLUDED.lease_until
`

type UpsertExecutionLeaseParams struct {
	Key        string
	Owner      string
	Epoch      int64
	LeaseUntil int64
}

func (q *Queries) UpsertExecutionLease(ctx context.Context, arg UpsertExecutionLeaseParams) error {
	_, err := q.db.Exec(ctx, upsertExecutionLease,
		arg.Key,
		arg.Owner,
		arg.Epoch,
		arg.LeaseUntil,
	)
	return err
}
