// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox.sql

package db

import (
	"context"
)

const inboxEntry = `-- name: InboxEntry :one
SELECT seq, command_id, kind, payload, enqueued_at, status, reason, resolved_at
FROM inbox WHERE session = $1 AND command_id = $2
`

type InboxEntryParams struct {
	Session   string
	CommandID string
}

type InboxEntryRow struct {
	Seq        int64
	CommandID  string
	Kind       string
	Payload    string
	EnqueuedAt int64
	Status     string
	Reason     string
	ResolvedAt int64
}

func (q *Queries) InboxEntry(ctx context.Context, arg InboxEntryParams) (InboxEntryRow, error) {
	row := q.db.QueryRow(ctx, inboxEntry, arg.Session, arg.CommandID)
	var i InboxEntryRow
	err := row.Scan(
		&i.Seq,
		&i.CommandID,
		&i.Kind,
		&i.Payload,
		&i.EnqueuedAt,
		&i.Status,
		&i.Reason,
		&i.ResolvedAt,
	)
	return i, err
}

const inboxNextSeq = `-- name: InboxNextSeq :one
SELECT (COALESCE(MAX(seq), -1) + 1)::bigint AS next_seq FROM inbox WHERE session = $1
`

func (q *Queries) InboxNextSeq(ctx context.Context, session string) (int64, error) {
	row := q.db.QueryRow(ctx, inboxNextSeq, session)
	var next_seq int64
	err := row.Scan(&next_seq)
	return next_seq, err
}

const inboxPending = `-- name: InboxPending :many
SELECT seq, command_id, kind, payload, enqueued_at, status, reason, resolved_at
FROM inbox WHERE session = $1 AND status = '' ORDER BY seq
`

type InboxPendingRow struct {
	Seq        int64
	CommandID  string
	Kind       string
	Payload    string
	EnqueuedAt int64
	Status     string
	Reason     string
	ResolvedAt int64
}

func (q *Queries) InboxPending(ctx context.Context, session string) ([]InboxPendingRow, error) {
	rows, err := q.db.Query(ctx, inboxPending, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxPendingRow{}
	for rows.Next() {
		var i InboxPendingRow
		if err := rows.Scan(
			&i.Seq,
			&i.CommandID,
			&i.Kind,
			&i.Payload,
			&i.EnqueuedAt,
			&i.Status,
			&i.Reason,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inboxSessions = `-- name: InboxSessions :many
SELECT DISTINCT session FROM inbox WHERE status = '' ORDER BY session LIMIT $1
`

func (q *Queries) InboxSessions(ctx context.Context, limit int32) ([]string, error) {
	rows, err := q.db.Query(ctx, inboxSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var session string
		if err := rows.Scan(&session); err != nil {
			return nil, err
		}
		items = append(items, session)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInboxEntry = `-- name: InsertInboxEntry :exec
INSERT INTO inbox (session, seq, command_id, kind, payload, enqueued_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertInboxEntryParams struct {
	Session    string
	Seq        int64
	CommandID  string
	Kind       string
	Payload    string
	EnqueuedAt int64
}

func (q *Queries) InsertInboxEntry(ctx context.Context, arg InsertInboxEntryParams) error {
	_, err := q.db.Exec(ctx, insertInboxEntry,
		arg.Session,
		arg.Seq,
		arg.CommandID,
		arg.Kind,
		arg.Payload,
		arg.EnqueuedAt,
	)
	return err
}

const resolveInboxEntry = `-- name: ResolveInboxEntry :execrows
UPDATE inbox SET status = $1, reason = $2, resolved_at = $3 WHERE session = $4 AND seq = $5 AND status = ''
`

type ResolveInboxEntryParams struct {
	Status     string
	Reason     string
	ResolvedAt int64
	Session    string
	Seq        int64
}

func (q *Queries) ResolveInboxEntry(ctx context.Context, arg ResolveInboxEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveInboxEntry,
		arg.Status,
		arg.Reason,
		arg.ResolvedAt,
		arg.Session,
		arg.Seq,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
