// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Binding struct {
	ID      string
	Digest  string
	Binding string
}

type Checkpoint struct {
	Consumer string
	Ledger   string
	Next     int64
}

type Claim struct {
	ID             string
	OwnerKind      string
	OwnerAuthority string
	OwnerIdentity  string
	State          string
	Claim          string
}

type Content struct {
	Authority  string
	Key        string
	Data       []byte
	MediaType  string
	Durability string
}

type Execution struct {
	Key           string
	AssignmentKey string
}

type ExecutionCommit struct {
	Key      string
	Seq      int64
	CommitID string
	Body     string
}

type ExecutionLease struct {
	Key        string
	Owner      string
	Epoch      int64
	LeaseUntil int64
}

type Inbox struct {
	Session    string
	Seq        int64
	CommandID  string
	Kind       string
	Payload    string
	EnqueuedAt int64
	Status     string
	Reason     string
	ResolvedAt int64
}

type Process struct {
	Key           string
	AssignmentKey string
	Epoch         int64
}

type ProcessCommit struct {
	Key      string
	Seq      int64
	CommitID string
	Body     string
}

type ProjectionCache struct {
	Session    string
	Projection string
	Version    int64
	State      string
	Through    int64
}

type SessionCommit struct {
	Segment  string
	Seq      int64
	CommitID string
	Body     string
}

type SessionCommitStream struct {
	Segment  string
	Seq      int64
	Domain   string
	StreamID string
	Events   int64
}

type SessionRoot struct {
	ID         string
	Tip        string
	CreatedAt  int64
	Epoch      int64
	Owned      bool
	Owner      string
	LeaseUntil int64
	Failed     string
}

type SessionSegment struct {
	ID     string
	Header string
}

type TwilightSchema struct {
	Version   int64
	AppliedAt int64
}

type Workspace struct {
	ID     string
	Record string
}

type WorkspaceSnapshot struct {
	Ref       string
	Workspace string
	Record    string
}
