// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processes.sql

package db

import (
	"context"
)

const insertProcess = `-- name: InsertProcess :exec
INSERT INTO processes (key, assignment_key, epoch) VALUES ($1, $2, $3)
`

type InsertProcessParams struct {
	Key           string
	AssignmentKey string
	Epoch         int64
}

func (q *Queries) InsertProcess(ctx context.Context, arg InsertProcessParams) error {
	_, err := q.db.Exec(ctx, insertProcess, arg.Key, arg.AssignmentKey, arg.Epoch)
	return err
}

const insertProcessCommit = `-- name: InsertProcessCommit :exec
INSERT INTO process_commits (key, seq, commit_id, body) VALUES ($1, $2, $3, $4)
`

type InsertProcessCommitParams struct {
	Key      string
	Seq      int64
	CommitID string
	Body     string
}

func (q *Queries) InsertProcessCommit(ctx context.Context, arg InsertProcessCommitParams) error {
	_, err := q.db.Exec(ctx, insertProcessCommit,
		arg.Key,
		arg.Seq,
		arg.CommitID,
		arg.Body,
	)
	return err
}

const processCommitSeq = `-- name: ProcessCommitSeq :one
SELECT seq FROM process_commits WHERE key = $1 AND commit_id = $2
`

type ProcessCommitSeqParams struct {
	Key      string
	CommitID string
}

func (q *Queries) ProcessCommitSeq(ctx context.Context, arg ProcessCommitSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, processCommitSeq, arg.Key, arg.CommitID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const processCommitsFrom = `-- name: ProcessCommitsFrom :many
SELECT seq, body FROM process_commits WHERE key = $1 AND seq >= $2 ORDER BY seq
`

type ProcessCommitsFromParams struct {
	Key string
	Seq int64
}

type ProcessCommitsFromRow struct {
	Seq  int64
	Body string
}

func (q *Queries) ProcessCommitsFrom(ctx context.Context, arg ProcessCommitsFromParams) ([]ProcessCommitsFromRow, error) {
	rows, err := q.db.Query(ctx, processCommitsFrom, arg.Key, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcessCommitsFromRow{}
	for rows.Next() {
		var i ProcessCommitsFromRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const processEpoch = `-- name: ProcessEpoch :one
SELECT epoch FROM processes WHERE key = $1
`

func (q *Queries) ProcessEpoch(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRow(ctx, processEpoch, key)
	var epoch int64
	err := row.Scan(&epoch)
	return epoch, err
}

const processHead = `-- name: ProcessHead :one
SELECT COALESCE(MAX(seq), -1)::bigint AS last_seq FROM process_commits WHERE key = $1
`

func (q *Queries) ProcessHead(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRow(ctx, processHead, key)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const raiseProcessEpoch = `-- name: RaiseProcessEpoch :exec
UPDATE processes SET epoch = GREATEST(epoch, $1) WHERE key = $2
`

type RaiseProcessEpochParams struct {
	Epoch int64
	Key   string
}

func (q *Queries) RaiseProcessEpoch(ctx context.Context, arg RaiseProcessEpochParams) error {
	_, err := q.db.Exec(ctx, raiseProcessEpoch, arg.Epoch, arg.Key)
	return err
}
