// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projections.sql

package db

import (
	"context"
)

const deleteProjectionEntries = `-- name: DeleteProjectionEntries :exec
DELETE FROM projection_cache WHERE session = $1
`

func (q *Queries) DeleteProjectionEntries(ctx context.Context, session string) error {
	_, err := q.db.Exec(ctx, deleteProjectionEntries, session)
	return err
}

const projectionEntry = `-- name: ProjectionEntry :one
SELECT state, through FROM projection_cache WHERE session = $1 AND projection = $2 AND version = $3
`

type ProjectionEntryParams struct {
	Session    string
	Projection string
	Version    int64
}

type ProjectionEntryRow struct {
	State   string
	Through int64
}

func (q *Queries) ProjectionEntry(ctx context.Context, arg ProjectionEntryParams) (ProjectionEntryRow, error) {
	row := q.db.QueryRow(ctx, projectionEntry, arg.Session, arg.Projection, arg.Version)
	var i ProjectionEntryRow
	err := row.Scan(&i.State, &i.Through)
	return i, err
}

const upsertProjectionEntry = `-- name: UpsertProjectionEntry :exec
INSERT INTO projection_cache (session, projection, version, state, through) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session, projection, version) DO UPDATE SET state = EXCLUDED.state, through = EXCLUDED.through
WHERE projection_cache.through < EXCLUDED.through
`

type UpsertProjectionEntryParams struct {
	Session    string
	Projection string
	Version    int64
	State      string
	Through    int64
}

func (q *Queries) UpsertProjectionEntry(ctx context.Context, arg UpsertProjectionEntryParams) error {
	_, err := q.db.Exec(ctx, upsertProjectionEntry,
		arg.Session,
		arg.Projection,
		arg.Version,
		arg.State,
		arg.Through,
	)
	return err
}
