// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOrphanPathSpans = `-- name: DeleteOrphanPathSpans :exec
DELETE FROM session_path_spans AS s
WHERE NOT EXISTS (
	SELECT 1 FROM session_roots AS r
	WHERE r.id = s.session AND NOT r.deleted
)
`

func (q *Queries) DeleteOrphanPathSpans(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOrphanPathSpans)
	return err
}

const deleteSegment = `-- name: DeleteSegment :exec
DELETE FROM session_segments WHERE id = $1
`

func (q *Queries) DeleteSegment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSegment, id)
	return err
}

const deleteSegmentCommitStreams = `-- name: DeleteSegmentCommitStreams :exec
DELETE FROM session_commit_streams WHERE segment = $1
`

func (q *Queries) DeleteSegmentCommitStreams(ctx context.Context, segment string) error {
	_, err := q.db.Exec(ctx, deleteSegmentCommitStreams, segment)
	return err
}

const deleteSegmentCommitStreamsAbove = `-- name: DeleteSegmentCommitStreamsAbove :exec
DELETE FROM session_commit_streams WHERE segment = $1 AND seq > $2
`

type DeleteSegmentCommitStreamsAboveParams struct {
	Segment string
	Seq     int64
}

func (q *Queries) DeleteSegmentCommitStreamsAbove(ctx context.Context, arg DeleteSegmentCommitStreamsAboveParams) error {
	_, err := q.db.Exec(ctx, deleteSegmentCommitStreamsAbove, arg.Segment, arg.Seq)
	return err
}

const deleteSegmentCommits = `-- name: DeleteSegmentCommits :exec
DELETE FROM session_commits WHERE segment = $1
`

func (q *Queries) DeleteSegmentCommits(ctx context.Context, segment string) error {
	_, err := q.db.Exec(ctx, deleteSegmentCommits, segment)
	return err
}

const deleteSegmentCommitsAbove = `-- name: DeleteSegmentCommitsAbove :exec
DELETE FROM session_commits WHERE segment = $1 AND seq > $2
`

type DeleteSegmentCommitsAboveParams struct {
	Segment string
	Seq     int64
}

func (q *Queries) DeleteSegmentCommitsAbove(ctx context.Context, arg DeleteSegmentCommitsAboveParams) error {
	_, err := q.db.Exec(ctx, deleteSegmentCommitsAbove, arg.Segment, arg.Seq)
	return err
}

const deleteSessionPathSpans = `-- name: DeleteSessionPathSpans :exec
DELETE FROM session_path_spans WHERE session = $1
`

func (q *Queries) DeleteSessionPathSpans(ctx context.Context, session string) error {
	_, err := q.db.Exec(ctx, deleteSessionPathSpans, session)
	return err
}

const expiredSessionRoots = `-- name: ExpiredSessionRoots :many
SELECT id, tip, created_at, epoch, owned, owner, lease_until, failed, deleted FROM session_roots
WHERE owned AND NOT deleted AND lease_until > 0 AND lease_until <= $1 ORDER BY lease_until, id LIMIT $2
`

type ExpiredSessionRootsParams struct {
	Before   int64
	RowLimit int32
}

func (q *Queries) ExpiredSessionRoots(ctx context.Context, arg ExpiredSessionRootsParams) ([]SessionRoot, error) {
	rows, err := q.db.Query(ctx, expiredSessionRoots, arg.Before, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionRoot{}
	for rows.Next() {
		var i SessionRoot
		if err := rows.Scan(
			&i.ID,
			&i.Tip,
			&i.CreatedAt,
			&i.Epoch,
			&i.Owned,
			&i.Owner,
			&i.LeaseUntil,
			&i.Failed,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldSessionRoots = `-- name: HeldSessionRoots :many
SELECT id, tip, created_at, epoch, owned, owner, lease_until, failed, deleted FROM session_roots WHERE owned AND NOT deleted ORDER BY id
`

func (q *Queries) HeldSessionRoots(ctx context.Context) ([]SessionRoot, error) {
	rows, err := q.db.Query(ctx, heldSessionRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionRoot{}
	for rows.Next() {
		var i SessionRoot
		if err := rows.Scan(
			&i.ID,
			&i.Tip,
			&i.CreatedAt,
			&i.Epoch,
			&i.Owned,
			&i.Owner,
			&i.LeaseUntil,
			&i.Failed,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPathSpan = `-- name: InsertPathSpan :exec
INSERT INTO session_path_spans (session, ordinal, segment, from_seq, through_seq) VALUES ($1, $2, $3, $4, $5)
`

type InsertPathSpanParams struct {
	Session    string
	Ordinal    int64
	Segment    string
	FromSeq    int64
	ThroughSeq pgtype.Int8
}

func (q *Queries) InsertPathSpan(ctx context.Context, arg InsertPathSpanParams) error {
	_, err := q.db.Exec(ctx, insertPathSpan,
		arg.Session,
		arg.Ordinal,
		arg.Segment,
		arg.FromSeq,
		arg.ThroughSeq,
	)
	return err
}

const insertSegment = `-- name: InsertSegment :exec
INSERT INTO session_segments (id, header, parent_segment) VALUES ($1, $2, $3)
`

type InsertSegmentParams struct {
	ID            string
	Header        string
	ParentSegment pgtype.Text
}

func (q *Queries) InsertSegment(ctx context.Context, arg InsertSegmentParams) error {
	_, err := q.db.Exec(ctx, insertSegment, arg.ID, arg.Header, arg.ParentSegment)
	return err
}

const insertSegmentCommit = `-- name: InsertSegmentCommit :exec
INSERT INTO session_commits (segment, seq, commit_id, body) VALUES ($1, $2, $3, $4)
`

type InsertSegmentCommitParams struct {
	Segment  string
	Seq      int64
	CommitID string
	Body     string
}

func (q *Queries) InsertSegmentCommit(ctx context.Context, arg InsertSegmentCommitParams) error {
	_, err := q.db.Exec(ctx, insertSegmentCommit,
		arg.Segment,
		arg.Seq,
		arg.CommitID,
		arg.Body,
	)
	return err
}

const insertSegmentCommitStream = `-- name: InsertSegmentCommitStream :exec
INSERT INTO session_commit_streams (segment, seq, domain, stream_id, events) VALUES ($1, $2, $3, $4, $5)
`

type InsertSegmentCommitStreamParams struct {
	Segment  string
	Seq      int64
	Domain   string
	StreamID string
	Events   int64
}

func (q *Queries) InsertSegmentCommitStream(ctx context.Context, arg InsertSegmentCommitStreamParams) error {
	_, err := q.db.Exec(ctx, insertSegmentCommitStream,
		arg.Segment,
		arg.Seq,
		arg.Domain,
		arg.StreamID,
		arg.Events,
	)
	return err
}

const insertSessionRoot = `-- name: InsertSessionRoot :exec
INSERT INTO session_roots (id, tip, created_at) VALUES ($1, $2, $3)
`

type InsertSessionRootParams struct {
	ID        string
	Tip       string
	CreatedAt int64
}

func (q *Queries) InsertSessionRoot(ctx context.Context, arg InsertSessionRootParams) error {
	_, err := q.db.Exec(ctx, insertSessionRoot, arg.ID, arg.Tip, arg.CreatedAt)
	return err
}

const livePathSpans = `-- name: LivePathSpans :many
SELECT s.session, s.ordinal, s.segment, s.from_seq, s.through_seq
FROM session_path_spans s
JOIN session_roots r ON r.id = s.session
WHERE NOT r.deleted
ORDER BY s.session, s.ordinal
`

func (q *Queries) LivePathSpans(ctx context.Context) ([]SessionPathSpan, error) {
	rows, err := q.db.Query(ctx, livePathSpans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPathSpan{}
	for rows.Next() {
		var i SessionPathSpan
		if err := rows.Scan(
			&i.Session,
			&i.Ordinal,
			&i.Segment,
			&i.FromSeq,
			&i.ThroughSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const segment = `-- name: Segment :one
SELECT header FROM session_segments WHERE id = $1
`

func (q *Queries) Segment(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, segment, id)
	var header string
	err := row.Scan(&header)
	return header, err
}

const segmentCommitAt = `-- name: SegmentCommitAt :one
SELECT seq FROM session_commits WHERE segment = $1 AND seq = $2
`

type SegmentCommitAtParams struct {
	Segment string
	Seq     int64
}

func (q *Queries) SegmentCommitAt(ctx context.Context, arg SegmentCommitAtParams) (int64, error) {
	row := q.db.QueryRow(ctx, segmentCommitAt, arg.Segment, arg.Seq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const segmentCommitByID = `-- name: SegmentCommitByID :one
SELECT body FROM session_commits WHERE segment = $1 AND commit_id = $2
`

type SegmentCommitByIDParams struct {
	Segment  string
	CommitID string
}

func (q *Queries) SegmentCommitByID(ctx context.Context, arg SegmentCommitByIDParams) (string, error) {
	row := q.db.QueryRow(ctx, segmentCommitByID, arg.Segment, arg.CommitID)
	var body string
	err := row.Scan(&body)
	return body, err
}

const segmentCommitSeq = `-- name: SegmentCommitSeq :one
SELECT seq FROM session_commits WHERE segment = $1 AND commit_id = $2
`

type SegmentCommitSeqParams struct {
	Segment  string
	CommitID string
}

func (q *Queries) SegmentCommitSeq(ctx context.Context, arg SegmentCommitSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, segmentCommitSeq, arg.Segment, arg.CommitID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const segmentCommitsFrom = `-- name: SegmentCommitsFrom :many
SELECT seq, body FROM session_commits WHERE segment = $1 AND seq >= $2 ORDER BY seq LIMIT $3
`

type SegmentCommitsFromParams struct {
	Segment string
	Seq     int64
	Limit   int32
}

type SegmentCommitsFromRow struct {
	Seq  int64
	Body string
}

func (q *Queries) SegmentCommitsFrom(ctx context.Context, arg SegmentCommitsFromParams) ([]SegmentCommitsFromRow, error) {
	rows, err := q.db.Query(ctx, segmentCommitsFrom, arg.Segment, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentCommitsFromRow{}
	for rows.Next() {
		var i SegmentCommitsFromRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const segmentHead = `-- name: SegmentHead :one
SELECT COALESCE(MAX(seq), -1)::bigint AS last_seq FROM session_commits WHERE segment = $1
`

func (q *Queries) SegmentHead(ctx context.Context, segment string) (int64, error) {
	row := q.db.QueryRow(ctx, segmentHead, segment)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const segmentIDs = `-- name: SegmentIDs :many
SELECT id FROM session_segments ORDER BY id
`

func (q *Queries) SegmentIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, segmentIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const segmentIndex = `-- name: SegmentIndex :many
SELECT seq, commit_id FROM session_commits WHERE segment = $1 ORDER BY seq
`

type SegmentIndexRow struct {
	Seq      int64
	CommitID string
}

func (q *Queries) SegmentIndex(ctx context.Context, segment string) ([]SegmentIndexRow, error) {
	rows, err := q.db.Query(ctx, segmentIndex, segment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentIndexRow{}
	for rows.Next() {
		var i SegmentIndexRow
		if err := rows.Scan(&i.Seq, &i.CommitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const segmentIndexSummary = `-- name: SegmentIndexSummary :one
SELECT COUNT(*)::bigint AS entries, COALESCE(MIN(seq), -1)::bigint AS first_seq, COALESCE(MAX(seq), -1)::bigint AS last_seq FROM session_commits WHERE segment = $1
`

type SegmentIndexSummaryRow struct {
	Entries  int64
	FirstSeq int64
	LastSeq  int64
}

func (q *Queries) SegmentIndexSummary(ctx context.Context, segment string) (SegmentIndexSummaryRow, error) {
	row := q.db.QueryRow(ctx, segmentIndexSummary, segment)
	var i SegmentIndexSummaryRow
	err := row.Scan(&i.Entries, &i.FirstSeq, &i.LastSeq)
	return i, err
}

const segmentReferenced = `-- name: SegmentReferenced :one
SELECT (EXISTS (SELECT 1 FROM session_roots WHERE tip = $1 AND NOT deleted)
    OR EXISTS (SELECT 1 FROM session_segments WHERE parent_segment = $1))::boolean AS referenced
`

func (q *Queries) SegmentReferenced(ctx context.Context, tip string) (bool, error) {
	row := q.db.QueryRow(ctx, segmentReferenced, tip)
	var referenced bool
	err := row.Scan(&referenced)
	return referenced, err
}

const segmentSpanBound = `-- name: SegmentSpanBound :one
SELECT through_seq FROM session_path_spans WHERE segment = $1 ORDER BY through_seq DESC NULLS FIRST LIMIT 1
`

func (q *Queries) SegmentSpanBound(ctx context.Context, segment string) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, segmentSpanBound, segment)
	var through_seq pgtype.Int8
	err := row.Scan(&through_seq)
	return through_seq, err
}

const segmentStreamCommits = `-- name: SegmentStreamCommits :many
SELECT c.seq, c.body FROM session_commits c
JOIN session_commit_streams s ON s.segment = c.segment AND s.seq = c.seq
WHERE c.segment = $1 AND s.domain = $2 AND s.stream_id = $3 AND c.seq >= $4 AND s.events > 0
ORDER BY c.seq LIMIT $5
`

type SegmentStreamCommitsParams struct {
	Segment  string
	Domain   string
	StreamID string
	Seq      int64
	Limit    int32
}

type SegmentStreamCommitsRow struct {
	Seq  int64
	Body string
}

func (q *Queries) SegmentStreamCommits(ctx context.Context, arg SegmentStreamCommitsParams) ([]SegmentStreamCommitsRow, error) {
	rows, err := q.db.Query(ctx, segmentStreamCommits,
		arg.Segment,
		arg.Domain,
		arg.StreamID,
		arg.Seq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentStreamCommitsRow{}
	for rows.Next() {
		var i SegmentStreamCommitsRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const segmentStreamCounts = `-- name: SegmentStreamCounts :many
SELECT seq, domain, stream_id, events FROM session_commit_streams WHERE segment = $1 ORDER BY seq, domain, stream_id
`

type SegmentStreamCountsRow struct {
	Seq      int64
	Domain   string
	StreamID string
	Events   int64
}

func (q *Queries) SegmentStreamCounts(ctx context.Context, segment string) ([]SegmentStreamCountsRow, error) {
	rows, err := q.db.Query(ctx, segmentStreamCounts, segment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentStreamCountsRow{}
	for rows.Next() {
		var i SegmentStreamCountsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Domain,
			&i.StreamID,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const segmentStreamHead = `-- name: SegmentStreamHead :one
SELECT COALESCE(SUM(events), 0)::bigint AS events FROM session_commit_streams WHERE segment = $1 AND domain = $2 AND stream_id = $3 AND seq < $4
`

type SegmentStreamHeadParams struct {
	Segment  string
	Domain   string
	StreamID string
	Seq      int64
}

func (q *Queries) SegmentStreamHead(ctx context.Context, arg SegmentStreamHeadParams) (int64, error) {
	row := q.db.QueryRow(ctx, segmentStreamHead,
		arg.Segment,
		arg.Domain,
		arg.StreamID,
		arg.Seq,
	)
	var events int64
	err := row.Scan(&events)
	return events, err
}

const sessionPathSpans = `-- name: SessionPathSpans :many
SELECT ordinal, segment, from_seq, through_seq FROM session_path_spans WHERE session = $1 ORDER BY ordinal
`

type SessionPathSpansRow struct {
	Ordinal    int64
	Segment    string
	FromSeq    int64
	ThroughSeq pgtype.Int8
}

func (q *Queries) SessionPathSpans(ctx context.Context, session string) ([]SessionPathSpansRow, error) {
	rows, err := q.db.Query(ctx, sessionPathSpans, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPathSpansRow{}
	for rows.Next() {
		var i SessionPathSpansRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.Segment,
			&i.FromSeq,
			&i.ThroughSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionRoot = `-- name: SessionRoot :one
SELECT id, tip, created_at, epoch, owned, owner, lease_until, failed, deleted FROM session_roots WHERE id = $1
`

func (q *Queries) SessionRoot(ctx context.Context, id string) (SessionRoot, error) {
	row := q.db.QueryRow(ctx, sessionRoot, id)
	var i SessionRoot
	err := row.Scan(
		&i.ID,
		&i.Tip,
		&i.CreatedAt,
		&i.Epoch,
		&i.Owned,
		&i.Owner,
		&i.LeaseUntil,
		&i.Failed,
		&i.Deleted,
	)
	return i, err
}

const sessionRoots = `-- name: SessionRoots :many
SELECT id, tip, created_at, epoch, owned, owner, lease_until, failed, deleted FROM session_roots WHERE NOT deleted ORDER BY id
`

func (q *Queries) SessionRoots(ctx context.Context) ([]SessionRoot, error) {
	rows, err := q.db.Query(ctx, sessionRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionRoot{}
	for rows.Next() {
		var i SessionRoot
		if err := rows.Scan(
			&i.ID,
			&i.Tip,
			&i.CreatedAt,
			&i.Epoch,
			&i.Owned,
			&i.Owner,
			&i.LeaseUntil,
			&i.Failed,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstoneSessionRoot = `-- name: TombstoneSessionRoot :exec
UPDATE session_roots SET deleted = TRUE, owned = FALSE, owner = '', lease_until = 0, failed = '' WHERE id = $1
`

func (q *Queries) TombstoneSessionRoot(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, tombstoneSessionRoot, id)
	return err
}

const updateSessionOwnership = `-- name: UpdateSessionOwnership :exec
UPDATE session_roots SET epoch = $1, owned = $2, owner = $3, lease_until = $4, failed = $5 WHERE id = $6
`

type UpdateSessionOwnershipParams struct {
	Epoch      int64
	Owned      bool
	Owner      string
	LeaseUntil int64
	Failed     string
	ID         string
}

func (q *Queries) UpdateSessionOwnership(ctx context.Context, arg UpdateSessionOwnershipParams) error {
	_, err := q.db.Exec(ctx, updateSessionOwnership,
		arg.Epoch,
		arg.Owned,
		arg.Owner,
		arg.LeaseUntil,
		arg.Failed,
		arg.ID,
	)
	return err
}
