// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"
)

const insertWorkspace = `-- name: InsertWorkspace :exec
INSERT INTO workspaces (id, record) VALUES ($1, $2)
`

type InsertWorkspaceParams struct {
	ID     string
	Record string
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error {
	_, err := q.db.Exec(ctx, insertWorkspace, arg.ID, arg.Record)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
UPDATE workspaces SET record = $1 WHERE id = $2
`

type UpdateWorkspaceParams struct {
	Record string
	ID     string
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.Exec(ctx, updateWorkspace, arg.Record, arg.ID)
	return err
}

const upsertWorkspaceSnapshot = `-- name: UpsertWorkspaceSnapshot :exec
INSERT INTO workspace_snapshots (ref, workspace, record) VALUES ($1, $2, $3)
ON CONFLICT (ref) DO UPDATE SET workspace = EXCLUDED.workspace, record = EXCLUDED.record
`

type UpsertWorkspaceSnapshotParams struct {
	Ref       string
	Workspace string
	Record    string
}

func (q *Queries) UpsertWorkspaceSnapshot(ctx context.Context, arg UpsertWorkspaceSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertWorkspaceSnapshot, arg.Ref, arg.Workspace, arg.Record)
	return err
}

const workspace = `-- name: Workspace :one
SELECT record FROM workspaces WHERE id = $1
`

func (q *Queries) Workspace(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, workspace, id)
	var record string
	err := row.Scan(&record)
	return record, err
}

const workspaceSnapshot = `-- name: WorkspaceSnapshot :one
SELECT record FROM workspace_snapshots WHERE ref = $1
`

func (q *Queries) WorkspaceSnapshot(ctx context.Context, ref string) (string, error) {
	row := q.db.QueryRow(ctx, workspaceSnapshot, ref)
	var record string
	err := row.Scan(&record)
	return record, err
}
